version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DB_NAME
    networks:
      - backend-network

  mongo1:
    image: mongo
    container_name: mongo1
    restart: unless-stopped
    volumes:
      - ./scripts/mongo-rs-init.sh:/scripts/mongo-rs-init.sh
    networks:
      - backend-network
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  api:
    image: vitormsp/cooking_together_api
    container_name: api
    env_file: .env
    volumes:
      - ./scripts/run-migrations.sh:/cooking-together/run-migrations.sh
    networks:
      - backend-network
    ports:
      - $PORT:$PORT
    depends_on:
      - mysql
      - mongo1

networks:
  backend-network:
    driver: bridge