version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DB_NAME
    # volumes: 
    #   - dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - "3306:3306"
    # networks:
    #   - app-network


  mongo1:
    container_name: mongo1
    image: mongo
    volumes:
      - ./mongo-rs-init.sh:/scripts/mongo-rs-init.sh
    # networks:
    #   - mongo-network
    ports:
      - 27017:27017
    # restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  # api:
  #   container_name: api
  #   image: node
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - 3333:3333

# networks:
#   mongo-network:
#     driver: bridge