version: '3'

services:
  mongo1:
    container_name: mongo1
    image: mongo
    volumes:
      - ./mongo-rs-init.sh:/scripts/mongo-rs-init.sh
    networks:
      - mongo-network
    ports:
      - 27017:27017
    # restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  # api:
  #   container_name: api
  #   image: node
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - 3333:3333

networks:
  mongo-network:
    driver: bridge